# Generated by Django 5.1.1 on 2024-09-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('DRAFT', 'Черновик'), ('OPEN', 'Открыто'), ('CLOSED', 'Закрыто')], default='OPEN'),
        ),
    ]
